performed modifications after adding sqrt computation
Pi-Squared-Inc/solidity-demo-semantics pull request #26
Opened 2024-09-05 08:06 UTC by ovatman

Changes include:
- `UniswapV2Router02.addLiquidity()` and `UniswapV2Pair.mint()` functions are added (together with functions they use such as `math_sqrt()`)
- `testRouterAddLiquidity()` test added that checks for newly added functionality
- output from regression tests are updated

2024-09-05 16:05 UTC, mariaKt requested changes
I believe that this is failing due to compound assignment no longer being supported.

2024-09-09 16:35 UTC, dwightguth requested changes
Please also make sure you are applying the same modifications to the version of the contract in `test/regression/swaps.sol`. The two files differ slightly, but we want to keep them enough in sync that they are running the same computations. Also, that version is the only version that is currently being regression tested.

2024-09-09 16:37 UTC, dwightguth commented
I will happily investigate the failures in the semantics if there are any, but now that we have a working version of the semantics on one version of the contract, changes to the contract need to only go through if they don't break the semantics.

2024-09-09 16:40 UTC, dwightguth commented
Also, just fyi, auto formatting a file in the same PR that you make other modifications to that file is a bad idea; it makes it vastly more difficult to review the code.

2024-09-09 18:10 UTC, mariaKt commented
I tried this version of Uniswap locally, and it does not run. It fails in` setUp` (https://github.com/Pi-Squared-Inc/solidity-demo-semantics/blob/ca576a1fbbd9a7285831d16a1c08140f510a6e2e/test/examples/swaps/UniswapV2Swap.sol#L673). Looking very briefly, it seems that is attempts to create a `UniswapV2Swap` using two different constructors.
https://github.com/Pi-Squared-Inc/solidity-demo-semantics/blob/ca576a1fbbd9a7285831d16a1c08140f510a6e2e/test/examples/swaps/UniswapV2Swap.sol#L677
and
https://github.com/Pi-Squared-Inc/solidity-demo-semantics/blob/ca576a1fbbd9a7285831d16a1c08140f510a6e2e/test/examples/swaps/UniswapV2Swap.sol#L689
Only the one with 3 parameters exists though.

2024-09-10 21:27 UTC, dwightguth commented
Can you show me what the change to the contract and the resulting stuck configuration were?

2024-09-10 22:00 UTC, mariaKt commented
@dwightguth if you meant me: I make no changes to the contract, and simply added the transaction
```
txn(1, 2, 0, 1724300000, testRouterAddLiquidity, )
``` after the others (so it is similar to the  UniswapTest.txn file in this PR). Here is the stuck configuration.

[conf.txt](https://github.com/user-attachments/files/16955291/conf.txt)

2024-09-13 14:05 UTC, dwightguth approved these changes
I'm approving so as to make you not stuck, but please address my comment prior to merging.

2024-09-13 14:05 UTC, dwightguth commented on test/regression/swaps.txn
> +txn(1, 2, 0, 1724300000, testRouterAddLiquidity, )
This should not be here. This program tests just the swap function.

2024-09-16 05:21 UTC, merged