Introducing `transferFrom` function summary on `dAIMock`
Pi-Squared-Inc/solidity-demo-semantics pull request #58
Opened 2024-10-07 23:13 UTC by Robertorosmaninho

This PR adds the summarized rules regarding the program execution. The rule presented in this PR summarizes the function of `transferFrom` function on `dAIMock`.

By summarizing this function, we save 1265 steps.
(Without it, the program took 19055 steps, and after implementing it, the program took 17790 steps)

Wall Time to execute 1000 `testSwapSingleHopExactAmountIn` summarized:
- On `main` branch: `0.176s`
- On this branch: `0.163s`

Wall Time to execute 1000 `testSwapSingleHopExactAmountIn` without any summarization: `0.280s`

2024-10-08 16:05 UTC, mariaKt requested changes
I requested some changes, pertaining to adding side conditions to the rule. Please let me know if I have misunderstood anything.

2024-10-08 16:05 UTC, mariaKt commented on src/uniswap-summaries.md
> +        </contract-storage> [priority(40)]
This is definitely not a correct summary. I see no two cases, therefore this is only summarizing only one of the two branches (the if not taken). This is OK, if you did not intend to do both. But, the conditions that make sure this rule is not applicable if the condition is true are missing.
The requirement for the requires statement at the beginning is also missing.

2024-10-09 15:44 UTC, mariaKt requested changes

2024-10-09 15:44 UTC, mariaKt commented on src/uniswap-summaries.md
> +        <contract-address> THIS </contract-address>
You can match `<this-type>` and `<contract-id>` cells. I posted details on slack.

2024-10-09 15:44 UTC, mariaKt commented on src/uniswap-summaries.md
> +     andBool (V1 =/=MInt SENDER orBool {read(read({Storage [ allowance ] orDefault .Map}:>Value, ListItem(V1), (mapping ( address daiownr => mapping ( address daispdr => uint256 ) ))), ListItem(SENDE
Shouldn't this `orBool` be `andBool`?

2024-10-10 14:47 UTC, Robertorosmaninho commented on src/uniswap-summaries.md
> +     andBool (V1 =/=MInt SENDER orBool {read(read({Storage [ allowance ] orDefault .Map}:>Value, ListItem(V1), (mapping ( address daiownr => mapping ( address daispdr => uint256 ) ))), ListItem(SENDE
Right! My bad!

2024-10-10 16:23 UTC, mariaKt approved these changes
Approved. Thanks for addressing the comments.

2024-10-10 19:48 UTC, merged